### ISSUE TITLE
Add "jump ahead" button

### ISSUE THREAD

**Issue by davidhaselb** [soleil-alpin/Transcriptions#10]
Can you add a button to jump AHEAD and not just jump BEHIND?

Your app is great.

---

**Comment by JanX2** [comment]
@davidhaselb
Wouldn’t it make more sense to add coarse time navigation? Jumping backwards and forwards by a fixed amount. Say 10 seconds. In addition to replay/rewind.

**Comment by davidhaselb** [comment]
Added fast forward
