### ISSUE TITLE
Foot Pedal Support

### ISSUE THREAD

**Issue by lhamo55** [soleil-alpin/Transcriptions#11]
Please advise which foot pedals are compatible with Transcriptions. Need to purchase soon for heavy workload, thanks.

**Comment by davidhaselb** [comment]
Hello,

Any footpedal that outputs sort of a keyboard shortcut should work.
Transcriptions for example works very well with the pedals from audiotranskription.de => when you press on these pedals, they output the same as if you would press F4 on your keyboard.

For example, this one should work fine:
http://www.audiotranskription.de/shop/schreibplatz-science.html

(Maybe you want to check back with your supplier if the pedal outputs a keyboard shortcut.)

Kind regards,
David
