### ISSUE TITLE
Transcriptions - a must have for transcribers 

### ISSUE THREAD

**Issue by luisbittencourt** [soleil-alpin/Transcriptions#12]
This app was a good surprise. I’m have been doing my phd and part of the work is to transcribe hours and hours of interviews. Basically, this app does everything you may need for the job: you can run audio and video files and transcribe the information through its incorporated text editor; you can insert time stamps, which allows you to precisely find and listen specific parts of the audio/video file by just clicking on them; you can backwards and replay you can also insert substitutions (like phrases, personal names, expressions or whatever you want) just by shortcuts which you can also customize accordingly to your preferences. You can also slowdown the audio (without change the pitch!) which is very helpful to understand and transcribe tricky passages. It also has a useful RePlay function to listen again the previously seconds from the audio/video file and also customize the RePlay time from 0 to 10 seconds. I think this app is a great deal and does a lot for the price you pay for it, which is almost ten times less than other similar apps in the market (which is also a point to consider). It also has an option to contact the developer for suggestions and critics and I guess it will be improved even more with the participation of its users.

**Comment by JanX2** [comment]
@luisbittencourt Thank you for the review! 

This is the issue section for this project. Do you have any feedback as to improvements you would like to see? If that’s the case, please open a new issue. 

As an aside: what you pay is a donation and could in no way finance commercial development of such a piece of software. Transcriptions is OSS and a labor of love. :)
