### ISSUE TITLE
Media control setting changes only working inconsistently

### ISSUE THREAD

**Issue by timlb** [soleil-alpin/Transcriptions#13]
I've tried changing the replay time setting. Sometime it seems to work. But then, during a session, it will revert to a very short time. Once this has happened changes in the config window seem to make no difference. This is frustrating in a tool which is simple and good.

Version 1.2 (1.2.5)
OS 10.11.6 (15G1004)

**Comment by davidhaselb** [comment]
True, thank you for sharing your bug report. Can you say, how long a session usually is?
Is there a particular moment, when this happens? Can you reproduce the error?
Thank you for your help.
We will look into it and try to fix it as soon as possible.

Kind regards,
David

**Comment by JanX2** [comment]
Yes. This is a known issue. Currently a lot of settings are not handle correctly. The “replay time” is one of those. 

This will require some infrastructural changes and may take a while.

**Comment by timlb** [comment]
It happened again today. I was aware of it within about 3 minutes into the section I was transcribing. But I cannot replicate it, in the sense that I cannot work out what I did to trigger the problem.

Glad that you're aware of the problem and planning to fix.

**Comment by JanX2** [comment]
@timlb 
These and many other related issues appear to be fixed in my development brach. Please write to me via [my contact form](http://geheimwerk.de/werk/contact/), if you want to test the new release and provide feedback (“beta-test”). :)

**Comment by davidhaselb** [comment]
Consistency of settings after app restart increased through storing values in app preferences
