### ISSUE TITLE
My app doesn't work

### ISSUE THREAD

**Issue by swissal** [soleil-alpin/Transcriptions#14]
Hi there,

I've just bought your app and tried to use it but it did not write any transcript of the audio.
Can you help?

Than you.

**Comment by davidhaselb** [comment]
Hi,

Transcription is an app for manual transcription - which means that it doesn´t automatically transcribe by definition. Besides supporting manual transcription of audio- or video-material, Transcriptions doesn´t support sending sensitive data (e. g. of scientific interviews) through the Internet to servers that can translate audio to text. 

Kind regards,
David
