### ISSUE TITLE
Quick rewind 

### ISSUE THREAD

**Issue by michaelbmorar** [soleil-alpin/Transcriptions#15]
How do I do I quick 5 second rewind in Transcribing app? 
I see in media, there is an option for replay.
But I am looking for a hot key or a quick way to rewind as I transcribe.   I would imagine anyone transcribing would need this.  So, I am guessing its here and I Just can't find it. Thanks, Michael

**Comment by davidhaselb** [comment]
Hello Michael,

you can define a shortcut by going to the menu, and there to “Preferences”.
To select the time length of the rewind, click the button below the video screen with the three sliders. There you can select “RePlay” time length.

Kind regards,
David

**Comment by michaelbmorar** [comment]
Ok. And once I do, How to I utilize the shortcut, without going to the
upper horizontal toolbar?

Thanks
MM​


On Thu, Jan 19, 2017 at 2:24 PM, David Haselberger <notifications@github.com

**Comment by michaelbmorar** [comment]
Hi

THanks.  I am making the replay to a certain key combination.  But I cannot
get the hot key
 combination to work.  Only when I click on repay in the toolbar.  It just
keeps typing the key combination and not replaying.  I must be missing
something easy.
Please advise. Thanks,
Michael


On Thu, Jan 19, 2017 at 3:49 PM, Michael Morar <michael.morar@pepperdine.edu
> wrote:

> Ok. And once I do, How to I utilize the shortcut, without going to the
> upper horizontal toolbar?
>
> Thanks
> MM​
>
> Michael Morar
> Recovery&Evidence-Based Practice, Lab Manager
> Marriage and Family Therapist Trainee
> Working Under Clinical Supervision
> Pepperdine Community Counseling Center
> 18111 Von Karman Ave, Suite 401
> Irvine, CA 92612 Phone: 949-355-5679
>
> On Thu, Jan 19, 2017 at 2:24 PM, David Haselberger <

**Comment by JanX2** [comment]
@michaelbmorar 
The hot key combination should contain something like the Ctrl key or the Command key. Otherwise, something else might take precedence.

**Comment by michaelbmorar** [comment]
@JanX2  nad/or @davidhaselb   I have defined the shortcuts (command c) for example.  But they hot keys are not working once I define them. Any suggestions?  thanks Michael

**Comment by JanX2** [comment]
@michaelbmorar 
I am using “Ctrl-<”, which is working fine. “Cmd-C” is already used for “Copy” in the “Edit” menu.

**Comment by michaelbmorar** [comment]
thanks @JanX2, I have tried that and still having a problem.  I have a mac, wondering if that is the problem.

**Comment by JanX2** [comment]
@michaelbmorar 
Transcriptions runs on macOS only. Why would that be a problem? Could you please make a screenshot of your Preferences window and drag the screenshot file it into your next message here? 

[How to take a screenshot on your Mac](https://support.apple.com/en-us/HT201361)
[github Issue attachments](https://github.com/blog/1347-issue-attachments)

**Comment by JanX2** [comment]
@michaelbmorar
I am closing this issue. Please feel free to comment here, if you need it reopened. :)
