### ISSUE TITLE
CPU activity more than 100% on i7 MBP?

### ISSUE THREAD

**Issue by mirozahorak** [soleil-alpin/Transcriptions#18]
During playback of MP3 and editing document CPU activity rises to more than 100% often on Sierra. I noticed general sluggishness on Sierra MBP. Tested 2 of them and seems to be the same.

**Comment by davidhaselb** [comment]
That is interesting - particularly because MP3 playback is based on Apples AVKit. Do you get similar results in other MP3-players that use AVKit? How is playback in Quicktime or iTunes?

Thanks for your support!

Kind regards,
David

**Comment by mirozahorak** [comment]
No, other players are just fine. Around 1-2 %

**Comment by davidhaselb** [comment]
Do you know the model of the MBPs (e.g. 2017, 2016, …)? Is there any kind of console warning? 
Thanks for the feedback, we will look into it. 

Kind regards,
David

**Comment by mirozahorak** [comment]
One is 2017 and one is 2013.
i do not have a change to check for console now
It is happening 100% time, as soon as I hit play and stop as soon as I stop playback.

**Comment by davidhaselb** [comment]
Does this happen with every file or just one? If just with one, what kind of file is it? Is it supported by AVFoundation?
