### ISSUE TITLE
Transcriptions Mac v1.1

### ISSUE THREAD

**Issue by mbesecy** [soleil-alpin/Transcriptions#19]
All of a sudden Transcriptions v1.1 will not open on my Mac OSX 10.9.5.  I get a message box "Transcriptions quit unexpectedly."

I cannot reinstall Transcriptions version 1.1.  The APP Store tells me there is an update available.  When I go to my purchased apps, I get this message:  "The current version requires OS X 10.11 or later, but you can download the last compatible version."  The last compatible version window gives me a message that I need to have OSX:  "You must update to Mac OS X 10.11 in order to download and use this application." 

How do I resolve this?

**Comment by davidhaselb** [comment]
Hello,

The newest version of Transcription is only supports OSX 10.11.
There are two ways to go here:
1. Upgrading the OS (and profiting from security updates of the system) and downloading the updated version of Transcriptions from the App Store
2. Getting the old version of Transcriptions (for OSX 9 and below, not tested on 10.9): https://code.google.com/archive/p/transcriptions/downloads
[3.: you can try this hack - NOT RECOMMENDED:
https://apple.stackexchange.com/questions/17396/forcing-getting-app-to-run-on-lower-mac-osx-version] 

Kind regards,
David
