### ISSUE TITLE
[MacAppStore] Inconsistent information between provided version and compatible OS

### ISSUE THREAD

**Issue by kaorukobo** [soleil-alpin/Transcriptions#2]
I found and purchased this product on MacAppStore.

My OS version is 10.9 Mavericks. Although README.md tells that the compatible product version is 0.8, App on the store provides version 1.1 and it tells compatible OS version is 10.6.6 or later. 

Purchased App worked superficially but I met some wrong behaviors. Now I’m happy with alternatively downloaded version 0.8. 

I think that compatible OS information on AppStore should be fixed.

**Comment by davidhaselb** [comment]
Hello,

thank you for the info. I already asked to change the requirements on the app store. We try to fix this in the next update to the AppStore version.

Kind regards,
David
