### ISSUE TITLE
Transcribing YouTube videos

### ISSUE THREAD

**Issue by melissakinsey** [soleil-alpin/Transcriptions#21]
Can this app be used to transcribe captions for YouTube videos? I don't mind a little cutting and pasting to put the captions on the right screens, but I don't want to have to type the audio for every video I create. 

Thanks, 
Melissa

**Comment by JanX2** [comment]
You can use something like [KeepVid](http://keepvid.com) to save YouTube captions in SRT format and the video file in MP4 format. Transcriptions will import SRT files and allow you to add MP4 media. 

When you are done, you can export to SRT and import those on YouTube:
https://support.google.com/youtube/answer/2734796?hl=en

Cheers,
Jan

**Comment by melissakinsey** [comment]
Thanks!
