### ISSUE TITLE
Won't transcribe

### ISSUE THREAD

**Issue by paulpap** [soleil-alpin/Transcriptions#22]
Just purchased the software. Opened a WAV file and it just plays - no transcription. There aren't many instructions so I don't know if I'm doing anything wrong.

Please help - -

Paul

**Comment by JanX2** [comment]
@paulpap Transcriptions is a manual transcription tool. It probably would be named “Auto-Transcriptions” and the description on the App Store would not say the following otherwise:

    A rtf-text editor optimized for fast manual transcription of audio- or video material on the Mac. Now with subtitle editing support.

Please see issue #17 for further details.
