### ISSUE TITLE
Timestamp problems.

### ISSUE THREAD

**Issue by PNW68** [soleil-alpin/Transcriptions#23]
Hi there,

Not sure if anyone else has experienced this, but I've been working on a transcript of a soundfile that's about an hour long. The time logger and the timestamp keep getting the times wrong... anywhere between one and two minutes out while I'm transcribing.... has anyone else experienced this?

**Comment by davidhaselb** [comment]
Hello, what kind of audio file did you try to transcribe?

**Comment by PNW68** [comment]
Hey there,

It's .mp3 files. Happened on four so far. Not sure if it's impacting it, but I'm transcribing at a reduced speed setting.

**Comment by davidhaselb** [comment]
It possibly had to do with key-value observing of the time value
