### ISSUE TITLE
media file

### ISSUE THREAD

**Issue by pegasus107** [soleil-alpin/Transcriptions#24]
I have mp3 files that I need to transcribe. How can I use them with this app? I see it now. Sorry...Didn't realize it was there. :0)

**Comment by davidhaselb** [comment]
Hello,

the app is for manual transcription. Please load your mp3 into the media player, and adjust the speed appropriate for typing in the preferences.

Kind regards,
David

**Comment by pegasus107** [comment]
Thank you. I was able to figure it out. Works great !!! Wonderful app!

Peg

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidhaselb** [comment]
Awesome :) Enjoy!

Kind regards,
David
