### ISSUE TITLE
It is not possible to see the keyboard shortcut

### ISSUE THREAD

**Issue by marxo126** [soleil-alpin/Transcriptions#28]
Cannot see if I changed shortcut, complete white.

<img width="387" alt="Screenshot 2021-02-08 at 17 40 35" src="https://user-images.githubusercontent.com/4749548/107252740-f15ac200-6a35-11eb-86a0-579879a53d9c.png">

**Comment by davidhaselb** [comment]
Recording Keyboard Shortcuts is updated
