### ISSUE TITLE
Creating Short Cuts

### ISSUE THREAD

**Issue by nickwetta** [soleil-alpin/Transcriptions#3]
Hi there - I recently purchased the app, but I can't seem to figure out how to create keyboard short cuts for basic actions such as play/pause. It looks like it's possible under preferences, where it says play/pause. It says "click to record shortcut", but I'm not sure what that means. I click, but I'm not apply to type anything. Please advise. Thank you!!

**Comment by davidhaselb** [comment]
Hello,

please try to click inside the rounded rectangle, then the keyboard shortcut you would like to use. You need to use “ctrl” or “alt” or “cmd” + a key.
Hope this works for you,

Kind Regards,
David

**Comment by SByler** [comment]
Hi David,

I just downloaded Transcriptions and it looks cool. I've figured out how to record/use shortcuts. (Took me a minute to figure out a shortcut for play/pause only works if there isn't a superseding function for that key.) My only problem is with the replay function--it only seems to momentarily pause, not rewind at all. Am I missing something?
