### ISSUE TITLE
File -> Open vs. "Load File"-Button

### ISSUE THREAD

**Issue by gruzilla** [soleil-alpin/Transcriptions#30]
Using the File -> Open menu item
<img width="500" alt="image" src="https://user-images.githubusercontent.com/304847/142223962-2bbfb2b6-024b-4aa8-9a7d-93cc4c135647.png">
files with the extension ".aac" cannot be selected:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/304847/142224315-12317dcb-a91f-4aa8-ac2d-f136f873fa3e.png">

It works, however, using the "Load File"-Button, on top of the Media Preview inside the application:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/304847/142224454-12bee0b7-fedd-4530-af9e-28d042286cd8.png">

Maybe, the person who has created #27 is experiencing the same issue.

**Comment by davidhaselb** [comment]
Thanks for the information,

so far media can be loaded with the “load file” button. The UI could be improved to make it clearer to where media can be loaded.

Kind regards,
David

**Comment by davidhaselb** [comment]
Changed "Open..." to "Open Transcript..." while leaving "Open Media File..." in the "File"-Menu
