### ISSUE TITLE
Apple Silicon/M1 version (Universal App)

### ISSUE THREAD

**Issue by MetroidFusion** [soleil-alpin/Transcriptions#31]
Hi

Would it be possible for you to (re)compile this application as a universal app - for both Intel and Apple Silicon/M1 chips? It runs fine via Rosetta 2, but it would be really nice if one of my most beloved (and used!) applications ran natively on Apple Silicon/ARM :)

Thanks for making this extraordinarily awesome application - I've used it for years and love the way it looks and functions.

/M

**Comment by davidhaselb** [comment]
Hello, yes, expect a version recompiled for M1/ARM this summer,

All the best,
David

**Comment by MetroidFusion** [comment]
> Hello, yes, expect a version recompiled for M1/ARM this summer,
> 
> All the best, David

Hello David,

That sounds absolutely amazing (again, Transcriptions is one of my favorite apps/tools on MacOS) - I'm looking forward to the release! :)

/M

**Comment by davidhaselb** [comment]
ARM Support implemented
