### ISSUE TITLE
Crosstalk between windows

### ISSUE THREAD

**Issue by JamesPHoughton** [soleil-alpin/Transcriptions#5]
I'm noticing that when I have two windows of Transcriptions open, commands intended for one window will go to the other as well. Two specific things for now, but I'll post others if I find them:
1. Pressing 'return' creates a new line and a timestamp in the window I intend, but also creates a timestamp in the other window. 
2. Changing the playback rate in the media controls pane starts the second window's audio playing.

**Comment by davidhaselb** [comment]
Thank you for your bug reports. We will try to fix this with the next release.

Kind regards,
David

**Comment by JanX2** [comment]
@davidhaselb Should already be fixed in source.
